spring:
  application:
    name: wikigroup
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:postgresql://localhost:5432/wikigroup
    username: wikigroup_user
    password: wikigroup_pass

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
